USE ADMIN_DB;
SELECT * FROM ADMIN_KEY;
CREATE TABLE ADMIN_TABLE(
	KEY_ADMIN VARCHAR(6) NOT NULL
);
INSERT INTO ADMIN_TABLE(KEY_ADMIN)
VALUES ('ADMIN1');

INSERT INTO ADMIN_TABLE(KEY_ADMIN)
VALUES ('TCC123');

CREATE TABLE STUDENT_INFO(
	ID_NUMBER VARCHAR(10) PRIMARY KEY NOT NULL,
    FULLNAME VARCHAR(30) NOT NULL,
    TIME_IN DATETIME NOT NULL,
    TIME_OUT DATETIME
);

INSERT INTO STUDENT_INFO(ID_NUMBER, FULLNAME, TIME_IN,TIME_OUT)
VALUES ('2019-0880','RYAN JAY PASULOHAN','2023-10-14 15:30:00','2023-10-14 17:30:00');

SELECT * FROM STUDENT_INFO;

drop table STUDENT_INFO;

